version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100

  - package-ecosystem: "npm"
    directory: "/page"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100

  - package-ecosystem: "cargo"
    directory: "/src/backends/icicle-emulator/icicle-bridge/"
    schedule:
      interval: monthly
    open-pull-requests-limit: 100
